# Generated by Django 2.1.4 on 2018-12-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Math',
            new_name='Maths',
        ),
    ]
